### PR TITLE
Release candidate v1.1.0

### PR DESCRIPTION
**Pull request by Conjuror**
Release v1.1.0

- OBS support
- Add test cases for Amazon, Google Search, Gmail input lentency, Facebook
- Support Gecko Profiler webExtention version
- Suport Fx 55
- Iskakalunan for CI support is online
- Bug tuning and refactors

### CODE REVIEW

**Comment by ypwalter** [comment]
Please also make sure that #731 commit get picked. It should resolve the issue encountered.

**Comment by Conjuror** [comment]
@ypwalter #731 was picked

@ShakoHo According to the test result on the sample physical machine. Request for approving 💃

**Comment by Conjuror** [comment]
@ShakoHo Done

**Comment by ShakoHo** [comment]
@Conjuror you also need to squash the same commits in dev, or you will have conflicts when you merge code from dev to master next time.

**Comment by Conjuror** [comment]
done

**Pull request merged**
