### PR TITLE
refactor mailTask.py and related configures/commands

### PR DESCRIPTION
**Pull request by MarkYan**
refactor mail task

- remove redundant codes
- move configs to iskakalunan.json
- refactor mailTask.py for current log

### CODE REVIEW

**Comment by MarkYan** [comment]
@Conjuror @ShakoHo @ypwalter r?

**Comment by MarkYan** [comment]
@Conjuror @ShakoHo r?

**Comment by Conjuror** [comment]
Quick question... isn't this pr should go to dev? @MarkYan

**Comment by MarkYan** [comment]
Oops! Thanks for noticing! ><
I just changed it to dev. @Conjuror

**Pull request merged**
