### PR TITLE
Firefox configuration - part 3: Temporary Solution for current profiler zip file

### PR DESCRIPTION
**Pull request by askeing**
Temporary Solution for applying the settings to profiler, e.g. geckoprofiler, before the extensions part ready.

Ref: #493

### CODE REVIEW

**Comment by askeing** [comment]
@ShakoHo @MikeLien @ypwalter r?

**Comment by ypwalter** [comment]
r+, but don't merge until Monday (No merge code on Friday! XD)

**Comment by ypwalter** [comment]
r+ again for the new commit just checked in.

**Comment by ShakoHo** [comment]
lgtm r+

**Pull request merged**
