### PR TITLE
Implement Status/B2/BuildInfo support for PulseTrigger

### PR DESCRIPTION
**Pull request by askeing**
- Modify default template configs for Ejenti `customized topic` feature
- Add `run-hasal-on-specify-nightly` and `download-specify-nightly` commands into `cmd_config`
- Dynamic loading enabled platform list from PulseTrigger's `trigger_config` file
- Modify `trigger_config` for B2 support
- Implement and refactoring `TasksTrigger` Unittest cases
- String/List multiple support for `HasalTasks`' config `OVERWRITE_HASAL_SUITE_CASE_LIST`
- Implement PulseTrigger Status recoder
- Implement `lib.modules.buildInformation.BuildInformation` for handling build information from Archive/Treeherder

### CODE REVIEW

**Comment by askeing** [comment]
@ShakoHo @ypwalter r?

**Review by ShakoHo — APPROVED** [review]
lgtm

**Comment by askeing** [comment]
@ShakoHo @ypwalter @ycyen 
After this PR is merged, there are two new commands will be added into supported cmd list, `run-hasal-on-specify-nightly` and `download-specify-nightly`.
All agents have to pull new code and re-start for supporting new commands.

**Comment by askeing** [comment]
ref: #984

**Pull request merged**
